export class PostoSaude {
    constructor(
        public codCnes: number, 
        public codUnidade: string,
        public codIbge: number,
        public cnpj: string,
        public nomeFantasia: string,
        public natureza: string,
        public tipoUnidade: string,
        public esferaAdministrativa: string,
        public vinculoSus: string,
        public retencao: string,
        public fluxoClientela: string,
        public origemGeografica: string,
        public temAtendimentoUrgencia: string,
        public temAtendimentoAmbulatorial: string,
        public temCentroCirurgico: string,
        public temObstetra: string,
        public temNeoNatal: string,
        public temDialise: string,
        public descricaoCompleta: string,
        public tipoUnidadeCnes: string,
        public categoriaUnidade: string,
        public logradouro: string,
        public numero: string,
        public bairro: string,
        public cidade: string,
        public uf: string,
        public cep: string,
        public telefone: string,
        public turnoAtendimento: string,
        public lat: number,
        public long:  number
        ){}
    }